version: '3.8'

services:
  piano_detection:
    build: .
    container_name: piano_detection
    restart: unless-stopped
    environment:
      - RTSP_URL=${RTSP_URL}
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - PYTHONDONTWRITEBYTECODE=1  # Prevents writing .pyc files
    # volumes:
    #   - ./:/app
